name1=input("Enter Your Name: ")
name2=input("Enter Your Name: ")
name3=input("Enter Your Name: ")
name4=input("Enter Your Name: ")
name5=input("Enter Your Name: ")
b1=input("Enter Your Birthday (DD/MM/YYYY): ")
b2=input("Enter Your Birthday (DD/MM/YYYY): ")
b3=input("Enter Your Birthday (DD/MM/YYYY): ")
b4=input("Enter Your Birthday (DD/MM/YYYY): ")
b5=input("Enter Your Birthday (DD/MM/YYYY): ")

print("Person1: " + name1 + ", Birthday: " + b1)
print("Person2: " + name2 + ", Birthday: " + b2)
print("Person3: " + name3 + ", Birthday: " + b3)
print("Person4: " + name4 + ", Birthday: " + b4)
print("Person5: " + name5 + ", Birthday: " + b5)